# Generated by Powerlevel10k configuration wizard on 2023-11-21 at 19:45 CET.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh, checksum 42599.
# Wizard options: nerdfont-v3 + powerline, small icons, rainbow, unicode,
# round separators, round heads, round tails, 1 line, sparse, many icons, concise,
# transient_prompt, instant_prompt=verbose.
# Type `p10k configure` to generate another config.
#
# Config for Powerlevel10k with powerline prompt style with colorful background.
# Type `p10k configure` to generate your own config based on it.
#
# Tip: Looking for a nice color? Here's a one-liner to print colormap.
#
#   for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
    emulate -L zsh -o extended_glob

    # Unset all configuration options. This allows you to apply configuration changes without
    # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
    unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

    # Zsh >= 5.1 is required.
    [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

    # Left segment
    typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
        vi_mode
        vcs
        dir
    )

    # Right segment
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
        status
        command_execution_time
        battery
        time
        os_icon
    )

    # Icon font
    typeset -g POWERLEVEL9K_MODE=nerdfont-v3

    # When set to `moderate`, some icons will have an extra space after them. This is meant to avoid
    # icon overlap when using non-monospace fonts. When set to `none`, spaces are not added.
    typeset -g POWERLEVEL9K_ICON_PADDING=none

    # Add an empty line before each prompt.
    typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

    # Separator style
    typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='|'
    typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='|'
    typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4'
    typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6'
    typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
    typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'

    # Prompt style
    typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
    typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=2
    typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=1
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS,VIOWR}_CONTENT_EXPANSION='->'

    # Vi mode
    typeset -g POWERLEVEL9K_VI_MODE_FOREGROUND=0
    typeset -g POWERLEVEL9K_VI_COMMAND_MODE_STRING=NORMAL
    typeset -g POWERLEVEL9K_VI_VISUAL_MODE_STRING=VISUAL
    typeset -g POWERLEVEL9K_VI_OVERWRITE_MODE_STRING=REPLACE
    typeset -g POWERLEVEL9K_VI_INSERT_MODE_STRING=INSERT
    typeset -g POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND=14
    typeset -g POWERLEVEL9K_VI_MODE_VISUAL_BACKGROUND=5
    typeset -g POWERLEVEL9K_VI_MODE_OVERWRITE_BACKGROUND=3
    typeset -g POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND=6

    # Version contol system
    typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=15
    typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=15
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=15
    typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=15
    typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=7
    typeset -g POWERLEVEL9K_VCS_BACKGROUND=8

    # Directory
    typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
    typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
    typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
    typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
    typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
    typeset -g POWERLEVEL9K_DIR_FOREGROUND=15
    typeset -g POWERLEVEL9K_DIR_BACKGROUND=8

    # Status
    typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
    typeset -g POWERLEVEL9K_STATUS_OK=true
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
    typeset -g POWERLEVEL9K_STATUS_ERROR=true
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
    typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION=''
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION=''
    typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION=''
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION=''
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION=''
    typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
    typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=0
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0
    typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1
    typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=0
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=1
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=0
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=1
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=0

    # Command execution time
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION='祥'
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=7
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=0

    # Battery
    typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
    typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
    typeset -g POWERLEVEL9K_BATTERY_STAGES=''
    typeset -g POWERLEVEL9K_BATTERY_CHARGING_VISUAL_IDENTIFIER_EXPANSION=''
    typeset -g POWERLEVEL9K_BATTERY_LOW_VISUAL_IDENTIFIER_EXPANSION=''
    typeset -g POWERLEVEL9K_BATTERY_FOREGROUND=15
    typeset -g POWERLEVEL9K_BATTERY_BACKGROUND=8
    typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=1

    # Time
    typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M %p}'
    typeset -g POWERLEVEL9K_TIME_FOREGROUND=0
    typeset -g POWERLEVEL9K_TIME_BACKGROUND=6

    # OS identifier
    typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
    typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7

    # Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
    # For example, you can type POWERLEVEL9K_BACKGROUND=red and see your prompt turn red. Hot reload
    # can slow down prompt by 1-2 milliseconds, so it's better to keep it turned off unless you
    # really need it.
    typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

    # If p10k is already loaded, reload configuration.
    # This works even with POWERLEVEL9K_DISABLE_HOT_RELOAD=true.
    (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
