#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

#yabai -m config external_bar               all:32:0

yabai -m config mouse_follows_focus        off
yabai -m config focus_follows_mouse        off

yabai -m config window_animation_duration  0.35
yabai -m config window_origin_display      default
yabai -m config window_placement           second_child
yabai -m config window_topmost             off
yabai -m config window_shadow              on
yabai -m config window_opacity             off
yabai -m config window_opacity_duration    0.0
yabai -m config active_window_opacity      1.0
yabai -m config normal_window_opacity      1.0

yabai -m config window_border              off
yabai -m config window_border_width        1
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555

yabai -m config insert_feedback_color      0xffd75f5f
yabai -m config split_ratio                0.50
yabai -m config auto_balance               off
yabai -m config mouse_modifier             fn
yabai -m config mouse_action1              move
yabai -m config mouse_action2              resize
yabai -m config mouse_drop_action          swap

yabai -m config layout                     bsp
yabai -m config top_padding                20
yabai -m config bottom_padding             20
yabai -m config left_padding               20
yabai -m config right_padding              20
yabai -m config window_gap                 20

# Set padding depending on number of windows
#yabai -m signal --add event=window_created action="[[ $(yabai -m query --windows --space | jq 'length') -gt 1 ]] && \
#    yabai -m config top_padding 20 && \
#    yabai -m config bottom_padding 20 && \
#    yabai -m config left_padding 20 && \
#    yabai -m config right_padding 20"
#
## window_moved
#yabai -m signal --add event=window_destroyed action="[[ $(yabai -m query --windows --space | jq 'length') -lt 2 ]] && \
#    yabai -m config top_padding 40 && \
#    yabai -m config bottom_padding 40 && \
#    yabai -m config left_padding 80 && \
#    yabai -m config right_padding 80"

# Do not manage windows with certain titles eg. Copying files or moving to bin
yabai -m rule --add title="(Copy|Bin|Om den här datorn|Info)" manage=off

# Do not manage some apps which are not resizable
# Add homerow?
yabai -m rule --add app="^(Kalkylator|VLC|Systeminställningar|Homerow)$" manage=off

# ===== Rules ==================================

yabai -m rule --add label="Steam" app="^Steam$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
#yabai -m rule --add label="Safari" app="^Safari$" title="^(Allmänt|Flikar|Lösenord|Webbplatser|Tillägg|Autofyll|Sök|Säkerhet|Integritet|Avancerat)$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Aktivitetskontroll" app="^Aktivitetskontroll$" manage=off
yabai -m rule --add label="Kalkylator" app="^Kalkylator$" manage=off
yabai -m rule --add label="Ordbok" app="^Ordbok$" manage=off
yabai -m rule --add app="^Systeminställningar$" manage=off
yabai -m rule --add label="Programuppdatering" title="Programuppdatering" manage=off
yabai -m rule --add label="Om den här datorn" app="Systeminformation" title="Om den här datorn" manage=off

yabai -m space 1 --label code
yabai -m space 2 --label tex
yabai -m space 3 --label web
yabai -m space 4 --label idle
yabai -m space 5 --label misc
yabai -m space 6 --label doc
yabai -m space 7 --label help
yabai -m space 8 --label music
